name: RSpec Tests

on:
  push:
    branches: [ feature/get-ci-tests-up ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Check PostgreSQL connection
        run: nc -zv localhost 5432

      - name: Set up Database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
        run: |
          bin/rails db:create db:schema:load --trace

      - name: Run Tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
        run: |
          # db:migrate might not be necessary if db:schema:load is done unless you want to test migrations
          bin/rails db:migrate
          bundle exec rspec
