name: RuboCop

on: [push, pull_request]

jobs:
  rubocop-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install dependencies
      run: |
        bundle install
    - name: Run RuboCop
      run: |
        bundle exec rubocop
